#!/usr/bin/env bash

#
# Prunes old tracking branchs and removes any local branches that have been merged
#
# Before removing branches, it will prompt with an editable list so that some can be
# omitted.
#
# Excludes master branch
#

set -e

git fetch -p

# Ignore current branch and common git flow naming patterns
git branch --merged | grep -v -e "^\*" -e "master" -e "develop" >/tmp/merged-branches && \
  vi /tmp/merged-branches && \
  xargs git branch -d </tmp/merged-branches
